import java.io.*;
import java.net.*;

import com.google.transit.realtime.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
      try {
        URL url = new URL("https://data.edmonton.ca/download/7qed-k2fc/application%2Foctet-stream");
        URLConnection con = url.openConnection();
        GtfsRealtime.FeedMessage msg = GtfsRealtime.FeedMessage.parseFrom(con.getInputStream());
        System.out.println(msg.toString());
      } catch(Exception e) {
        e.printStackTrace();
      }
    }
}
