import java.io.*;
import java.net.*;
import java.util.*;

import com.google.transit.realtime.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static App app;
    public BusFeed busfeed;
    public BusTracker bustracker;

    public static void main(String[] args) {
        new App();
    }

    public App() {
        app = this;
        busfeed = new BusFeed(null);
        busfeed.startFeed();
        bustracker = new BusTracker();
        busfeed.setListener(bustracker);
        EmbeddedServer server = new EmbeddedServer(bustracker);
        while(true) {
            try {
                Thread.sleep(60000);
            } catch (Exception e) {}
        }
    }
}
